Adopcion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Aplicaciones.Adoptar.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Aplicaciones/Adoptar/urls.py
from django.urls import path
from . import views
#from .views import AgendarCitaView

urlpatterns = [
    path('', views.index, name='index'),
    path('lobby/', views.lobby, name='lobby'),
    path('lobby_org/', views.lobby_organizacion, name='lobby_organizacion'),
    #path('agendar_cita/<int:mascota_id>/', views.agendar_cita, name='agendar_cita'),
    path('login/', views.inicio_sesion, name='inicio_sesion'),
    path('registro/', views.registro, name='registro'),
    path('login_organizacion/', views.inicio_sesion_organizacion, name='inicio_sesion_organizacion'),
    path('registro_organizacion/', views.registro_organizacion, name='registro_organizacion'),
    path('galeria/<int:mascota_id>/', views.mostrar_galeria, name='galeria'),
    path('registro_mascota/', views.registrar_mascota, name='registro_mascota'),
    #path('registro_mascota/vista_org/', views.vista_organizacion, name='vista_org'),
    path('postulacion_adopcion/<int:mascota_id>/', views.postulacion_adopcion, name='postulacion_adopcion'),
    path('postulacion_adopcion/postulacion_exitosa', views.postulacion_exitosa, name='postulacion_exitosa'),
    path('seguimiento_mascota/<int:mascota_id>/', views.seguimiento_mascota, name='seguimiento_mascota'),
    path('seguimiento_mascota/seguimiento_exitoso', views.seguimiento_exitoso, name='seguimiento_exitoso'),
    path('listar_mascotas/', views.listar_mascotas, name='listar_mascotas'),
    path('eliminar_mascota/<int:mascota_id>/', views.eliminar_mascota, name='eliminar_mascota'),
    path('editar_mascota/<int:mascota_id>/', views.editar_mascota, name='editar_mascota'),
    path('crear_colecta/', views.crear_colecta, name='crear_colecta'),
    path('donar/<int:colecta_id>/', views.donar, name='donar'),
    path('editar_colecta/<int:colecta_id>/', views.editar_colecta, name='editar_colecta'),
    path('eliminar_colecta/<int:colecta_id>/', views.eliminar_colecta, name='eliminar_colecta'),
    path('listar_seguimientos/', views.listar_seguimientos, name='listar_seguimientos'),
]

Aplicaciones/Adoptar/models.py
from django.db import models
from .choices import sexos
from datetime import date
from django.contrib.auth.models import User
# Create your models here.

class Usuario(models.Model):
    nombre=models.CharField(max_length=50)
    apellido=models.CharField(max_length=50)
    email=models.EmailField()
    password=models.CharField(max_length=50)
    telefono=models.DecimalField(max_digits=10, decimal_places=0)
    #rol_adoptante=models.CharField()
    #rol_administrador=models.CharField()

class Organizacion(models.Model):
    nombre_organizacion=models.CharField(max_length=50)
    tipo_organizacion=models.CharField(max_length=50)
    descripcion_org=models.TextField()
    email_organizacion=models.EmailField()
    password_org=models.CharField(max_length=50, default='default_value')
    telefono_organizacion=models.DecimalField(max_digits=10, decimal_places=0)
    direccion=models.CharField(max_length=50)
    sitio_web=models.URLField()


    def __str__(self):
        texto = "{0}"
        return texto.format(self.nombre_organizacion)
    
class Sede(models.Model):
   nombre_sede = models.CharField(max_length=50, default=None)
   direccion_sede = models.CharField(max_length=50, default=None)
   region_sede = models.CharField(max_length=50, default=None)

class Especie(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre
    
class Raza(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre
    
class FotoMascota(models.Model):
    url_foto = models.URLField()
    imagen = models.ImageField(upload_to='fotos/', default='default.jpg')  # Cambia 'default.jpg' por el valor que desees

    def __str__(self):
        return f"Foto de {self.mascota.nombre_mascota}"

class Mascota(models.Model):
    nombre_mascota=models.CharField(max_length=50)
    especie = models.ForeignKey(Especie, on_delete=models.CASCADE)
    raza = models.ForeignKey(Raza, on_delete=models.CASCADE)
    color=models.CharField(max_length=50)
    sexo=models.CharField(max_length=1, choices=sexos, default='H')
    edad=models.IntegerField()
    fecha_rescate=models.DateField(default=date.today)
    descripcion=models.TextField()
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE, related_name='mascotas', default=None, null=True, blank=True)
    foto_mascota = models.ImageField(upload_to='imagenes', null=True, blank=True)
    sede = models.ForeignKey(Sede, on_delete=models.CASCADE, default=None, null=True, blank=True)
    #foto_mascota = models.ForeignKey(FotoMascota, on_delete=models.CASCADE, null=True, blank=True, default=None)
    #adoptante=models.ForeignKey(Usuario, on_delete=models.CASCADE)

    def __str__(self):
        texto = "{0} {1} ({2})"
        return texto.format(self.nombre_mascota, self.especie, self.edad)
    
    #Crear Sede para que las organizaciones tengan diferentes sedes y que se muestre en la mascota

    
class Region(models.Model):
    nombre_region=models.CharField(max_length=50)
    nombre_comuna=models.CharField(max_length=50)
    #mascotas=models.ForeignKey(Mascota, on_delete=models.CASCADE)
    organizaciones=models.ForeignKey(Organizacion, on_delete=models.CASCADE)


class CitaAdopcion(models.Model):
    fecha=models.DateField()
    hora=models.TimeField()
    estado_cita=models.CharField(max_length=50)
    adoptante=models.ForeignKey(Usuario, on_delete=models.CASCADE)
    mascota=models.ForeignKey(Mascota, on_delete=models.CASCADE)

class Postulacion(models.Model):
    nombre_completo = models.CharField(max_length=100)
    rut = models.CharField(max_length=15)
    telefono_contacto = models.CharField(max_length=15)
    actividad_economica = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField()
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    mascota=models.ForeignKey(Mascota, on_delete=models.CASCADE)

class SeguimientoAdopcion(models.Model):
    fecha=models.DateField()
    estado_seguimiento=models.CharField(max_length=50)
    adoptante=models.ForeignKey(User, on_delete=models.CASCADE)
    mascota=models.ForeignKey(Mascota, on_delete=models.CASCADE)

class RegistroVacuna(models.Model):
    vacuna=models.CharField(max_length=50)

    def __str__(self):
        texto = "{0}"
        return texto.format(self.vacuna)

class EstadoSalud(models.Model):
    descripcion = models.CharField(max_length=255, default='valor_predeterminado')


class Colecta(models.Model):
    organizacion = models.ForeignKey(Organizacion, on_delete=models.CASCADE)
    meta = models.DecimalField(max_digits=12, decimal_places=2)
    recaudado = models.DecimalField(max_digits=12, decimal_places=2, default=0)
    fecha_limite = models.DateField()
    descripcion = models.TextField()

class SeguimientoEstadoSalud(models.Model):
    foto_mascota_mia = models.ImageField(upload_to='imagenes', null=True, blank=True)
    vacuna_mascota = models.ForeignKey(RegistroVacuna, on_delete=models.CASCADE)
    fecha_vacuna = models.DateField()
    descripcion_estado_salud = models.TextField()
    adoptante = models.ForeignKey(User, on_delete=models.CASCADE)
    mascota = models.ForeignKey(Mascota, on_delete=models.CASCADE)

Aplicaciones/Adoptar/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Mascota, CitaAdopcion, FotoMascota, Organizacion, Postulacion, Raza, Especie, SeguimientoAdopcion, Sede, Colecta, SeguimientoEstadoSalud
from django.views import View
from django.contrib.auth.hashers import make_password
from .forms import FiltroMascotasForm, CitaForm, RegistroForm, AuthenticationForm, OrganizacionRegistroForm, OrganizacionLoginForm, PostulacionForm, SeguimientoAdopcionForm, MascotaForm, ColectaForm, SeguimientoEstadoSaludForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

def index(request):
   colectas = Colecta.objects.all()
   colectas_con_porcentaje = []
   for colecta in colectas:
       porcentaje_recaudado = (colecta.recaudado / colecta.meta) * 100
       colectas_con_porcentaje.append((colecta, porcentaje_recaudado))
   return render(request, 'index.html', {'colectas': colectas_con_porcentaje})


def lobby(request):
    mascotas = Mascota.objects.all()

    if request.method == 'GET':
        form = FiltroMascotasForm(request.GET)
        if form.is_valid():
            especie = form.cleaned_data.get('especie')
            raza = form.cleaned_data.get('raza')
            sexo = form.cleaned_data.get('sexo')

            if especie:
                mascotas = mascotas.filter(especie=especie)
            if raza:
                mascotas = mascotas.filter(raza=raza)
            if sexo:
                mascotas = mascotas.filter(sexo=sexo)

    else:
        form = FiltroMascotasForm()

    return render(request, 'lobby.html', {'mascotas': mascotas, 'form': form})

def lobby_organizacion(request):
    mascotas = Mascota.objects.all()

    if request.method == 'GET':
        form = FiltroMascotasForm(request.GET)
        if form.is_valid():
            especie = form.cleaned_data.get('especie')
            raza = form.cleaned_data.get('raza')
            sexo = form.cleaned_data.get('sexo')

            if especie:
                mascotas = mascotas.filter(especie=especie)
            if raza:
                mascotas = mascotas.filter(raza=raza)
            if sexo:
                mascotas = mascotas.filter(sexo=sexo)

    else:
        form = FiltroMascotasForm()

    return render(request, 'lobby_org.html', {'mascotas': mascotas, 'form': form})
    
#def agendar_cita(request, mascota_id):
    #mascota = get_object_or_404(Mascota, pk=mascota_id)

    #if request.method == 'POST':
        #form = CitaForm(request.POST)
        #if form.is_valid():
            #fecha = form.cleaned_data['fecha']
            #hora = form.cleaned_data['hora']

            # Guarda la cita en la base de datos
            #cita = CitaAdopcion.objects.create(mascota=mascota, fecha=fecha, hora=hora)
            
            # Puedes redirigir a otra página o realizar alguna otra acción
            #return redirect('lobby')  # Cambia 'nombre_de_la_vista' por la vista deseada

    #else:
        #form = CitaForm()

    #return render(request, 'agendar_cita.html', {'mascota': mascota, 'form': form})


def inicio_sesion(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # Autenticar al usuario
            user = authenticate(request, username=username, password=password)

            if user is not None:
                # Iniciar sesión
                login(request, user)

                # Redirigir al lobby (ajusta la URL según tu configuración)
                return redirect('lobby')

    else:
        form = AuthenticationForm()

    return render(request, 'inicio_sesion.html', {'form': form})

def registro(request):
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']

            # Crea el usuario
            user = User.objects.create_user(username=username, email=email, password=password)

            # Inicia sesión automáticamente después del registro
            login(request, user)

            # Redirige al lobby (ajusta la URL según tu configuración)
            return redirect('inicio_sesion')
    else:
        form = RegistroForm()

    return render(request, 'registro.html', {'form': form})

def inicio_sesion_organizacion(request):
    if request.method == 'POST':
        nombre_organizacion = request.POST.get('nombre_organizacion')
        password_org = request.POST.get('password_org')

        # Autenticar a la organización
        organizacion = authenticate(request, nombre_organizacion=nombre_organizacion, password_org=password_org)

        if organizacion is not None:
            # Iniciar sesión
            login(request, organizacion)

            # Redirigir a donde desees después de iniciar sesión
            return redirect('listar_mascotas')  # Ajusta la URL según tu configuración
        else:
            # Organización no encontrada o contraseña incorrecta
            messages.error(request, 'Nombre de organización o contraseña incorrectos. Inténtalo de nuevo.')
            return redirect('listar_mascotas')
        
    return render(request, 'inicio_sesion_org.html')



def registro_organizacion(request):
    if request.method == 'POST':
        form = OrganizacionRegistroForm(request.POST)
        if form.is_valid():
            # Obtener datos del formulario
            nombre_organizacion = form.cleaned_data['nombre_organizacion']
            tipo_organizacion = form.cleaned_data['tipo_organizacion']
            descripcion_org = form.cleaned_data['descripcion_org']
            email_organizacion = form.cleaned_data['email_organizacion']
            password_org = form.cleaned_data['password_org']
            telefono_organizacion = form.cleaned_data['telefono_organizacion']
            direccion = form.cleaned_data['direccion']
            sitio_web = form.cleaned_data['sitio_web']

            # Crear y guardar la organización en la base de datos
            Organizacion.objects.create(
                nombre_organizacion=nombre_organizacion,
                tipo_organizacion=tipo_organizacion,
                descripcion_org=descripcion_org,
                email_organizacion=email_organizacion,
                password_org=password_org,
                telefono_organizacion=telefono_organizacion,
                direccion=direccion,
                sitio_web=sitio_web
            )

            # Redirigir a donde desees después de registrar la organización
            return redirect('inicio_sesion_organizacion')  # Ajusta la URL según tus necesidades
    else:
        form = OrganizacionRegistroForm()

    return render(request, 'registro_org.html', {'form': form})


def mostrar_galeria(request, mascota_id):
    # Obtener la mascota seleccionada o devolver un error 404 si no existe
    mascota = get_object_or_404(Mascota, id=mascota_id)

    # Obtener todas las fotos asociadas a la mascota seleccionada
    fotos_mascota = FotoMascota.objects.filter(mascota=mascota)

    # Puedes realizar cualquier lógica adicional aquí según tus necesidades

    # Renderizar la plantilla de galería con las fotos de la mascota seleccionada
    return render(request, 'galeria.html', {'mascota': mascota, 'fotos_mascota': fotos_mascota})

def registrar_mascota(request):
    especies = Especie.objects.all()
    razas = Raza.objects.all()
    organizaciones = Organizacion.objects.all()

    if request.method == 'POST':
        # Obtén los datos del formulario
        nombre_mascota = request.POST['nombre_mascota']
        especie_id = request.POST['especie']
        raza_id = request.POST['raza']
        color = request.POST['color']
        sexo = request.POST['sexo']
        edad = request.POST['edad']
        fecha_rescate = request.POST['fecha_rescate']
        descripcion = request.POST['descripcion']
        organizacion_id = request.POST['organizacion']
        foto_mascota = request.FILES.get('fotos_mascota')

        # Obtén los datos de la sede del formulario
        nombre_sede = request.POST['nombre_sede']
        direccion_sede = request.POST['direccion_sede']
        region_sede = request.POST['region_sede']

        # Crea una nueva instancia de Sede
        sede = Sede.objects.create(
            nombre_sede=nombre_sede,
            direccion_sede=direccion_sede,
            region_sede=region_sede
        )

        # Obtén las instancias de Especie y Raza
        especie = Especie.objects.get(pk=especie_id)
        raza = Raza.objects.get(pk=raza_id)
        organizacion = Organizacion.objects.get(pk=organizacion_id)

        # Crea una nueva mascota
        nueva_mascota = Mascota.objects.create(
            nombre_mascota=nombre_mascota,
            especie=especie,
            raza=raza,
            color=color,
            sexo=sexo,
            edad=edad,
            fecha_rescate=fecha_rescate,
            descripcion=descripcion,
            organizacion=organizacion,
            foto_mascota=foto_mascota,
            sede=sede  # Asegúrate de que tu modelo Mascota tenga un campo 'sede' que sea una ForeignKey a Sede
        )

        # Redirige a donde desees después de crear la mascota
        return redirect('listar_mascotas')

    else:
        # Si el método no es POST, renderiza el formulario
        return render(request, 'registrar_mascota.html', {'especies': especies, 'razas': razas, 'organizaciones': organizaciones})

#def vista_organizacion(request):
    #organizaciones = Organizacion.objects.all()
    #razas = Raza.objects.all()

Aplicaciones/Adoptar/templates/crear_colecta.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
{% block content %}
  <div class="container">
    <h1 class="my-4">Crear Colecta</h1>
    <div class="card">
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
          {{ form.non_field_errors }}
          <div class="form-group">
            <label for="{{ form.meta.id_for_label }}">Meta:</label>
            {{ form.meta.errors }}
            {{ form.meta }}
          </div>
          <div class="form-group">
            <label for="{{ form.fecha_limite.id_for_label }}">Fecha límite:</label>
            {{ form.fecha_limite.errors }}
            {{ form.fecha_limite }}
          </div>
          <div class="form-group">
            <label for="{{ form.descripcion.id_for_label }}">Descripción:</label>
            {{ form.descripcion.errors }}
            {{ form.descripcion }}
          </div>
          <div class="form-group">
              <label for="{{ form.organizacion.id_for_label }}">Organización:</label>
              {{ form.organizacion.errors }}
              {{ form.organizacion }}
          </div>
          <button type="submit" class="btn btn-primary">Crear Colecta</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

Aplicaciones/Adoptar/templates/donar.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
{% block content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8">
        <div class="card mt-5">
          <div class="card-header bg-primary text-white">
            <h3 class="mb-0">Donar a {{ colecta.organizacion }}</h3>
          </div>
          <div class="card-body">
            <p class="card-text">Para hacer una donación, por favor envía un comprobante de pago al siguiente número de WhatsApp: (+56){{ colecta.organizacion.telefono_organizacion }}</p>
            <a href="#" class="btn btn-primary">Donar ahora</a>
            <button onclick="history.back()" class="btn btn-secondary mt-2">Regresar</button>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Aplicaciones/Adoptar/templates/listar_mascotas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Adoptame - Listado de mascotas</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>
<body>

    <div class="container">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <h1>Adoptame - Lobby Organizacion</h1>
            <div>
                <a href="{% url 'registro_mascota' %}" class="btn btn-primary mr-2">Ingresar nueva mascota</a>
                <a href="{% url 'crear_colecta' %}" class="btn btn-success">Crear colecta</a>
                {% for colecta in colectas %}
                <a href="{% url 'editar_colecta' colecta.id %}" class="btn btn-info">Editar Colecta</a>
                <a href="{% url 'eliminar_colecta' colecta.id %}" class="btn btn-danger">Eliminar Colecta</a>
                {% endfor %}
                <a href="{% url 'listar_seguimientos' %}" class="btn btn-secondary">Ver seguimientos</a>
            </div>
        </div>
        <div class="table-responsive py-2">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Especie</th>
                        <th>Raza</th>
                        <th>Color</th>
                        <th>Sexo</th>
                        <th>Edad</th>
                        <th>Descripción</th>
                        <th>Fecha de Rescate</th>
                        <th>Organización</th>
                        <th>Imagen</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for mascota in mascotas %}
                    <tr>
                        <td>{{ mascota.nombre_mascota }}</td>
                        <td>{{ mascota.especie }}</td>
                        <td>{{ mascota.raza }}</td>
                        <td>{{ mascota.color }}</td>
                        <td>{{ mascota.get_sexo_display }}</td>
                        <td>{{ mascota.edad }} años</td>
                        <td>{{ mascota.descripcion }}</td>
                        <td>{{ mascota.fecha_rescate }}</td>
                        <td>{{ mascota.organizacion }}</td>
                        <td>
                            {% if mascota.foto_mascota %}
                                <img src="{{ mascota.foto_mascota.url }}" alt="{{ mascota.nombre_mascota }}" style="max-width: 100px;">
                            {% else %}
                                No hay imagen
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'editar_mascota' mascota.id %}" class="btn btn-info">Editar</a>
                            <a href="{% url 'eliminar_mascota' mascota.id %}" class="btn btn-danger">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</body>
</html>

Aplicaciones/Adoptar/templates/lobby.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>Adoptame - Página de Inicio</title>
    <style>
        .card-img-top {
            width: 100%;
            height: 30vw;  /* Aumenta este valor para hacer la imagen más alta */
            object-fit: cover;
        }
        .card-img-overlay {
            background: rgba(0, 0, 0, 0.5);
            color: white;
        }
    </style>
</head>
<body>

    <div class="container">
        <h1 class="mt-4 mb-4">Bienvenido a Adoptame</h1>

        <!-- Barra de búsqueda -->
        <div class="card mb-4">
            <div class="card-body">
                <form method="get" class="form-inline">
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary ml-auto">Filtrar</button>
                </form>
            </div>
        </div>

        <div class="row">
            {% for mascota in mascotas %}
            <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4 mb-4">
                <div class="card bg-dark text-white">
                    {% if mascota.foto_mascota %}
                        <img src="{{ mascota.foto_mascota.url }}" class="card-img-top img-fluid" alt="{{ mascota.nombre_mascota }}">
                    {% else %}
                        <!-- Puedes agregar una imagen de marcador de posición si no hay foto -->
                        <img src="https://via.placeholder.com/300" class="card-img-top img-fluid" alt="Marcador de posición">
                    {% endif %}
                    <div class="card-img-overlay">
                        <h5 class="card-title">{{ mascota.nombre_mascota }}</h5>
                        <p class="card-text"> {{ mascota.especie }}</p>
                        <p class="card-text"> {{ mascota.raza }}</p>
                        <p class="card-text"> {{ mascota.get_sexo_display }}</p>
                        <p class="card-text"> {{ mascota.edad }} años aprox.</p>
                        <p class="card-text"> {{ mascota.organizacion }}</p>
                        <p class="card-text"> {{ mascota.sede.nombre_sede }}</p>
                        <p class="card-text"> {{ mascota.sede.region_sede }}</p>


                        <div class="d-flex justify-content-between align-items-center mt-4">
                            {% if mascota.id %}
                                <a href="{% url 'postulacion_adopcion' mascota.id %}" class="btn btn-success">Adoptar</a>
                                <a href="{% url 'seguimiento_mascota' mascota.id %}" class="btn btn-info">Seguimiento</a>
                            {% else %}
                                <p class="text-danger">No se puede generar la URL de adopción.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

Aplicaciones/Adoptar/templates/postulacion_adopcion.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>Postular para Adoptar a {{ mascota.nombre_mascota }}</title>
    <style>
        .card-img-top {
            width: 100%;
            height: 30vw; /* Adjust this value to change the height of the image */
            object-fit: fill; /* Change this to 'fill' to make the image stretch to fill the entire card */
        }
        .card-img-overlay {
            background: rgba(0, 0, 0, 0.5);
            color: white;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="my-4">Postular para Adoptar a {{ mascota.nombre_mascota }}</h1>

        <div class="card mb-4 bg-dark text-white">
            {% if mascota.foto_mascota %}
                <img src="{{ mascota.foto_mascota.url }}" class="card-img-top img-fluid" alt="{{ mascota.nombre_mascota }}">
            {% else %}
                <!-- Puedes agregar una imagen de marcador de posición si no hay foto -->
                <img src="https://via.placeholder.com/300" class="card-img-top img-fluid" alt="Marcador de posición">
            {% endif %}
            <div class="card-img-overlay">
                <h5 class="card-title">Información de la mascota:</h5>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-transparent">Especie: {{ mascota.especie }}</li>
                    <li class="list-group-item bg-transparent">Raza: {{ mascota.raza }}</li>
                    <li class="list-group-item bg-transparent">Color: {{ mascota.color }}</li>
                    <li class="list-group-item bg-transparent">Sexo: {{ mascota.get_sexo_display }}</li>
                    <li class="list-group-item bg-transparent">Edad: {{ mascota.edad }} años</li>
                    <li class="list-group-item bg-transparent">Descripción: {{ mascota.descripcion }}</li>
                </ul>
            </div>
        </div>

        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Postulación de Adopción</h2>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Enviar Postulación</button>
                </form>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>